### ISSUE TITLE
The should_failed check should preferably read should_fail instead

### ISSUE THREAD

**Issue by NoSuchCommand** [HewlettPackard/monkeyble#11]
As far as I understand the documentation, the intent of Monkeyble is to provide a declarative way of writing unit tests for Ansible tasks. To that end, the YAML keys used to describe the expected outcome of tasks should have a meaning when read out loud.

While it is the case for `should_be_changed` and `should_be skipped` checks, reading `should_failed` seems a little odd. I would suggest to change it to `should_fail` so that the reader can understand _this task **should fail**_ when reading the scenario.

**Comment by Sispheor** [comment]
Done and merged in dev branch. Will be part of the next release.
